### ISSUE TITLE
Documentação do Projeto

### ISSUE THREAD

**Issue by orlandosaraivajr** [GabrielVictorino8266/pi_1semestre#1]
Qual é o tema do software certo a ser feito ?

No dia 24/04, a equipe precisa ter claro qual o software o grupo pretende modelar, e apresentar os primeiros diagramas de **Caso de Uso**.

**Comment by GabrielVictorino8266** [comment]
**Aula 24/04/2024 - Diagramas de Caso de Uso**

![caso_de_uso drawio](https://github.com/GabrielVictorino8266/pi_1semestre/assets/72820281/a5058a0b-349e-48a8-861f-076e78683ec8)

[Projeto Grupo 7.pdf](https://github.com/GabrielVictorino8266/pi_1semestre/files/15102475/Projeto.Grupo.7.pdf)

Criador(es): Julio, Melissa
Auxiliar(es): Miran, Caio, Izabelly

**Comment by orlandosaraivajr** [comment]
o início da documentação ocorreu, mas não o término da atividade como um todo. Por isso acredito que esta issue poderia estar aberta ainda.

**Comment by orlandosaraivajr** [comment]
Em anexo, o template para a documentação, apresentado na aula de hoje.

Bom trabalho pessoal !
[Padrão Documentação ES1V1.odt](https://github.com/GabrielVictorino8266/pi_1semestre/files/15255731/Padrao.Documentacao.ES1V1.odt)

**Comment by GabrielVictorino8266** [comment]
> Em anexo, o template para a documentação, apresentado na aula de hoje.
> 
> Bom trabalho pessoal ! Uploading Padrão Documentação ES1V1.odt…

Professor, não consigo baixar.

**Comment by melissabvieira** [comment]
Professor o arquivo não abre

**Comment by orlandosaraivajr** [comment]
Em anexo, o template para a documentação, desta vez em formado .docx
Bom trabalho pessoal !
[Projeto Integrador 1º Semestre.docx](https://github.com/GabrielVictorino8266/pi_1semestre/files/15255725/Projeto.Integrador.1.Semestre.docx)

**Comment by orlandosaraivajr** [comment]
> > Em anexo, o template para a documentação, apresentado na aula de hoje.
> > Bom trabalho pessoal ! Uploading Padrão Documentação ES1V1.odt…
> 
> Professor, não consigo baixar.

Atualizado. Funcionou ?

**Comment by GabrielVictorino8266** [comment]
> > > Em anexo, o template para a documentação, apresentado na aula de hoje.
> > > Bom trabalho pessoal ! Uploading Padrão Documentação ES1V1.odt…
> > 
> > 
> > Professor, não consigo baixar.
> 
> Atualizado. Funcionou ?

Sim, deu certo. Obrigado. O Time já está atuando na demanda.
