### ISSUE TITLE
Design Digital - Definição de Usuário, Problema e Solução

### ISSUE THREAD

**Issue by GabrielVictorino8266** [GabrielVictorino8266/pi_1semestre#2]
**Question**
O que acharam da apresentação de design digital? Precisa melhorar algo?

**Comment by Julio-Saless** [comment]
Gostei e acredito eu que não tenha que alterar nada no momento, porque ficou bem completo

**Comment by caiobeteghellia** [comment]
Ficou bom, bem completo

**Comment by melissabvieira** [comment]
muito bom
