### ISSUE TITLE
Atualização Diagrama UML

### ISSUE THREAD

**Issue by GabrielVictorino8266** [GabrielVictorino8266/pi_1semestre#6]
**Sugestão de Melhoria de Diagrama Atividade UML - Fazer Login**
@Julio-Saless Júlio, dê uma olhada nesse diagrama, veja o que acha? Ele é especificamente para login.

**Comparação*
Versão by Gabriel
![Diagrama_Login](https://github.com/GabrielVictorino8266/pi_1semestre/assets/72820281/6efa13bb-9f5a-4051-9399-5c575617e07d)

Versão by Julio
![image](https://github.com/GabrielVictorino8266/pi_1semestre/assets/72820281/04147bdb-ec8e-4c63-a76a-15da7df3dc54)

**Comment by GabrielVictorino8266** [comment]
Sugestão de Melhoria de Diagrama Atividade UML - Fazer Cadastro
@Julio-Saless Júlio, dê uma olhada nesse diagrama, veja o que acha? Ele é especificamente para cadastro.

- Gabriel
![Diagrama_de_atividade-atividade-cadastrar](https://github.com/GabrielVictorino8266/pi_1semestre/assets/72820281/41db693e-dff1-4130-8f1f-2c6d9ecf2ac1)

-Julio
![image](https://github.com/GabrielVictorino8266/pi_1semestre/assets/72820281/e362bbba-427b-4765-aa33-8ded5c667ff6)

**Comment by Julio-Saless** [comment]
Eu gostei, acabou complementando os que eu fiz, com umas etapas a mais.
